// backgrounds/list.js — 背景图片清单，新增图片后在此添加一行即可
window.VN_BACKGROUNDS = [
  { name: "上午的街道", file: "上午的街道.jpeg" },
  { name: "中式厨房夜晚", file: "中式厨房夜晚.jpg" },
  { name: "串串", file: "串串.jpg" },
  { name: "傍晚巷子", file: "傍晚巷子.webp" },
  { name: "傍晚街道1", file: "傍晚街道1.webp" },
  { name: "傍晚街道2", file: "傍晚街道2.webp" },
  { name: "厨房夜晚", file: "厨房夜晚.webp" },
  { name: "咖啡店白天", file: "咖啡店白天.jpg" },
  { name: "夜晚商业街", file: "夜晚商业街.jpeg" },
  { name: "夜晚房间", file: "夜晚房间.webp" },
  { name: "夜晚街道1", file: "夜晚街道1.webp" },
  { name: "夜晚街道2", file: "夜晚街道2.webp" },
  { name: "女生房间傍晚", file: "女生房间傍晚.jpg" },
  { name: "女生房间夜晚", file: "女生房间夜晚.webp" },
  { name: "女生房间白天", file: "女生房间白天.webp" },
  { name: "女生房间白天2", file: "女生房间白天2.webp" },
  { name: "女生房间白天3", file: "女生房间白天3.jpg" },
  { name: "学校美术室傍晚", file: "学校美术室傍晚.jpg" },
  { name: "学校走廊傍晚", file: "学校走廊傍晚.webp" },
  { name: "学校走廊白天", file: "学校走廊白天.webp" },
  { name: "学校运动场下午", file: "学校运动场下午.jpg" },
  { name: "小房间白天", file: "小房间白天.webp" },
  { name: "居酒屋夜晚", file: "居酒屋夜晚.jpeg" },
  { name: "拉面店", file: "拉面店.webp" },
  { name: "教室傍晚", file: "教室傍晚.webp" },
  { name: "教室白天", file: "教室白天.webp" },
  { name: "无人樱花街道", file: "无人樱花街道.webp" },
  { name: "林荫街道", file: "林荫街道.webp" },
  { name: "樱花小道", file: "樱花小道.webp" },
  { name: "清晨小路", file: "清晨小路.webp" },
  { name: "清晨街道", file: "清晨街道.webp" },
  { name: "男生房间夜晚", file: "男生房间夜晚.webp" },
  { name: "男生房间白天", file: "男生房间白天.jpg" },
  { name: "蛋糕卷", file: "蛋糕卷.jpg" }
];
